version: '3.8'

services:
  pyspark:
    image: bitnami/spark:3.4.1
    container_name: abap_short_pyspark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=pyspark
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./:/app
      - ./data:/data
      - ./output:/output
      - ./logs:/logs
    working_dir: /app
    command: >
      bash -c "pip install --upgrade pip &&
               pip install -r requirements.txt &&
               tail -f /dev/null"
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge